# Phân tích khám phá về chất lượng rượu vang đỏ (Red Wine Quality)


## 1. Định nghĩa vấn đề (Define Problem)
- **Mô tả**:
    - Tập “Red Vinho Verde” (Bồ Đào Nha) thuộc bộ Wine Quality gốc UCI, được mirror trên Kaggle. Dữ liệu chỉ gồm thử nghiệm hoá lý và điểm cảm quan “quality”.
+ **Dữ liệu vào**:
    - fixed acidity: 
    - volatile acidity
    - citric acid
    - residual sugar 
    - chlorides
    - free sulfur dioxide 
    - total sulfur dioxide 
    - density, pH
    - sulphates
    - alcohol
+ **Kết quả**: quality (3-8)

## 2. Chuẩn bị vấn đề (Prepare Problem)

### 2.1. Khai báo thư viện (Load Libraries)

In [2]:
# Importing all import python libraries
import pandas as pd
from IPython import display
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### 2.2. Nạp dữ liệu (Load Dataset)

In [17]:
winequality_df = pd.read_csv("winequality-red.csv")
winequality_df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [ ]:
print(f"Content Unique columns:")
print(f"Fixed acidity: {np.sort(winequality_df["quality"].unique())}")
print(f"volatile acidity: {np.sort(winequality_df["volatile acidity"].unique())}")
print(f"citric acid: {np.sort(winequality_df["citric acid"].unique())}")
print(f"residual sugar: {np.sort(winequality_df["residual sugar"].unique())}")
print(f"chlorides: {np.sort(winequality_df["chlorides"].unique())}")
print(f"free sulfur dioxide: {np.sort(winequality_df["free sulfur dioxide"].unique())}")
print(f"total sulfur dioxide: {np.sort(winequality_df["total sulfur dioxide"].unique())}")
print(f"density: {np.sort(winequality_df["density"].unique())}")
print(f"pH: {np.sort(winequality_df["pH"].unique())}")
print(f"sulphates: {np.sort(winequality_df["sulphates"].unique())}")
print(f"alcohol: {np.sort(winequality_df["alcohol"].unique())}")
print(f"quality: {np.sort(winequality_df["quality"].unique())}")

Content Unique columns:
Fixed acidity: [3 4 5 6 7 8] /n
volatile acidity: [0.12  0.16  0.18  0.19  0.2   0.21  0.22  0.23  0.24  0.25  0.26  0.27
 0.28  0.29  0.295 0.3   0.305 0.31  0.315 0.32  0.33  0.34  0.35  0.36
 0.365 0.37  0.38  0.39  0.395 0.4   0.41  0.415 0.42  0.43  0.44  0.45
 0.46  0.47  0.475 0.48  0.49  0.5   0.51  0.52  0.53  0.54  0.545 0.55
 0.56  0.565 0.57  0.575 0.58  0.585 0.59  0.595 0.6   0.605 0.61  0.615
 0.62  0.625 0.63  0.635 0.64  0.645 0.65  0.655 0.66  0.665 0.67  0.675
 0.68  0.685 0.69  0.695 0.7   0.705 0.71  0.715 0.72  0.725 0.73  0.735
 0.74  0.745 0.75  0.755 0.76  0.765 0.77  0.775 0.78  0.785 0.79  0.795
 0.8   0.805 0.81  0.815 0.82  0.825 0.83  0.835 0.84  0.845 0.85  0.855
 0.86  0.865 0.87  0.875 0.88  0.885 0.89  0.895 0.9   0.91  0.915 0.92
 0.935 0.95  0.955 0.96  0.965 0.975 0.98  1.    1.005 1.01  1.02  1.025
 1.035 1.04  1.07  1.09  1.115 1.13  1.18  1.185 1.24  1.33  1.58 ]
citric acid: [0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.78 0.79 1.  ]
residual sugar: [ 0.9   1.2   1.3   1.4   1.5   1.6   1.65  1.7   1.75  1.8   1.9   2.
  2.05  2.1   2.15  2.2   2.25  2.3   2.35  2.4   2.5   2.55  2.6   2.65
  2.7   2.8   2.85  2.9   2.95  3.    3.1   3.2   3.3   3.4   3.45  3.5
  3.6   3.65  3.7   3.75  3.8   3.9   4.    4.1   4.2   4.25  4.3   4.4
  4.5   4.6   4.65  4.7   4.8   5.    5.1   5.15  5.2   5.4   5.5   5.6
  5.7   5.8   5.9   6.    6.1   6.2   6.3   6.4   6.55  6.6   6.7   7.
  7.2   7.3   7.5   7.8   7.9   8.1   8.3   8.6   8.8   8.9   9.   10.7
 11.   12.9  13.4  13.8  13.9  15.4  15.5 ]
chlorides: [0.012 0.034 0.038 0.039 0.041 0.042 0.043 0.044 0.045 0.046 0.047 0.048
 0.049 0.05  0.051 0.052 0.053 0.054 0.055 0.056 0.057 0.058 0.059 0.06
 0.061 0.062 0.063 0.064 0.065 0.066 0.067 0.068 0.069 0.07  0.071 0.072
 0.073 0.074 0.075 0.076 0.077 0.078 0.079 0.08  0.081 0.082 0.083 0.084
 0.085 0.086 0.087 0.088 0.089 0.09  0.091 0.092 0.093 0.094 0.095 0.096
 0.097 0.098 0.099 0.1   0.101 0.102 0.103 0.104 0.105 0.106 0.107 0.108
 0.109 0.11  0.111 0.112 0.113 0.114 0.115 0.116 0.117 0.118 0.119 0.12
 0.121 0.122 0.123 0.124 0.125 0.126 0.127 0.128 0.132 0.136 0.137 0.143
 0.145 0.146 0.147 0.148 0.152 0.153 0.157 0.159 0.161 0.165 0.166 0.168
 0.169 0.17  0.171 0.172 0.174 0.176 0.178 0.186 0.19  0.194 0.2   0.205
 0.213 0.214 0.216 0.222 0.226 0.23  0.235 0.236 0.241 0.243 0.25  0.263
 0.267 0.27  0.332 0.337 0.341 0.343 0.358 0.36  0.368 0.369 0.387 0.401
 0.403 0.413 0.414 0.415 0.422 0.464 0.467 0.61  0.611]
free sulfur dioxide: [ 1.   2.   3.   4.   5.   5.5  6.   7.   8.   9.  10.  11.  12.  13.
 14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.
 28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  37.5 38.  39.  40.
 40.5 41.  42.  43.  45.  46.  47.  48.  50.  51.  52.  53.  54.  55.
 57.  66.  68.  72. ]
total sulfur dioxide: [  6.    7.    8.    9.   10.   11.   12.   13.   14.   15.   16.   17.
  18.   19.   20.   21.   22.   23.   24.   25.   26.   27.   28.   29.
  30.   31.   32.   33.   34.   35.   36.   37.   38.   39.   40.   41.
  42.   43.   44.   45.   46.   47.   48.   49.   50.   51.   52.   53.
  54.   55.   56.   57.   58.   59.   60.   61.   62.   63.   64.   65.
  66.   67.   68.   69.   70.   71.   72.   73.   74.   75.   76.   77.
  77.5  78.   79.   80.   81.   82.   83.   84.   85.   86.   87.   88.
  89.   90.   91.   92.   93.   94.   95.   96.   98.   99.  100.  101.
 102.  103.  104.  105.  106.  108.  109.  110.  111.  112.  113.  114.
 115.  116.  119.  120.  121.  122.  124.  125.  126.  127.  128.  129.
 130.  131.  133.  134.  135.  136.  139.  140.  141.  142.  143.  144.
 145.  147.  148.  149.  151.  152.  153.  155.  160.  165.  278.  289. ]
density: [0.99007 0.9902  0.99064 0.9908  0.99084 0.9912  0.9915  0.99154 0.99157
 0.9916  0.99162 0.9917  0.99182 0.99191 0.9921  0.9922  0.99235 0.99236
 0.9924  0.99242 0.99252 0.99256 0.99258 0.99264 0.9927  0.9928  0.99286
 0.9929  0.99292 0.99294 0.99306 0.99314 0.99316 0.99318 0.9932  0.99322
 0.99323 0.99328 0.9933  0.99331 0.99332 0.99334 0.99336 0.9934  0.99341
 0.99344 0.99346 0.99348 0.9935  0.99352 0.99354 0.99356 0.99357 0.99358
 0.9936  0.99362 0.99364 0.9937  0.99371 0.99374 0.99376 0.99378 0.99379
 0.9938  0.99384 0.99385 0.99386 0.99387 0.99388 0.99392 0.99394 0.99395
 0.99396 0.99397 0.994   0.99402 0.99408 0.9941  0.99414 0.99416 0.99417
 0.99418 0.99419 0.9942  0.99425 0.99426 0.99428 0.9943  0.99434 0.99437
 0.99438 0.99439 0.9944  0.99444 0.99448 0.99451 0.99454 0.99456 0.99458
 0.99459 0.9946  0.99462 0.99464 0.99467 0.99468 0.9947  0.99471 0.99472
 0.99473 0.99474 0.99476 0.99478 0.99479 0.9948  0.99483 0.99484 0.99486
 0.99488 0.99489 0.9949  0.99491 0.99492 0.99494 0.99495 0.99496 0.99498
 0.99499 0.995   0.99501 0.99502 0.99504 0.99506 0.99508 0.99509 0.9951
 0.99512 0.99514 0.99516 0.99517 0.99518 0.99519 0.9952  0.99521 0.99522
 0.99523 0.99524 0.99525 0.99526 0.99528 0.99529 0.9953  0.99531 0.99532
 0.99533 0.99534 0.99536 0.99538 0.9954  0.99541 0.99542 0.99543 0.99544
 0.99545 0.99546 0.99547 0.99549 0.9955  0.99551 0.99552 0.99553 0.99554
 0.99555 0.99556 0.99557 0.99558 0.9956  0.99562 0.99564 0.99565 0.99566
 0.99568 0.99569 0.9957  0.99572 0.99573 0.99574 0.99575 0.99576 0.99577
 0.99578 0.9958  0.99581 0.99582 0.99584 0.99585 0.99586 0.99587 0.99588
 0.99589 0.9959  0.99592 0.99593 0.99594 0.99596 0.99598 0.99599 0.996
 0.99603 0.99604 0.99605 0.99606 0.99608 0.99609 0.9961  0.99612 0.99613
 0.99614 0.99615 0.99616 0.99617 0.99619 0.9962  0.99621 0.99622 0.99623
 0.99624 0.99625 0.99627 0.99628 0.99629 0.9963  0.99631 0.99632 0.99633
 0.99634 0.99635 0.99636 0.99638 0.99639 0.9964  0.99641 0.99642 0.99643
 0.99645 0.99646 0.99647 0.99648 0.99649 0.9965  0.99651 0.99652 0.99654
 0.99655 0.99656 0.99658 0.99659 0.9966  0.99661 0.99664 0.99665 0.99666
 0.99667 0.99668 0.99669 0.9967  0.99672 0.99674 0.99675 0.99676 0.99677
 0.99678 0.9968  0.99682 0.99683 0.99684 0.99685 0.99686 0.99688 0.99689
 0.9969  0.99692 0.99693 0.99694 0.99695 0.99697 0.99698 0.99699 0.997
 0.99701 0.99702 0.99704 0.99705 0.99706 0.99708 0.99709 0.9971  0.99712
 0.99713 0.99714 0.99716 0.99717 0.99718 0.99719 0.9972  0.99721 0.99722
 0.99724 0.99725 0.99726 0.99727 0.99728 0.99729 0.9973  0.99732 0.99733
 0.99734 0.99735 0.99736 0.99738 0.99739 0.9974  0.99743 0.99744 0.99745
 0.99746 0.99747 0.99748 0.9975  0.99752 0.99754 0.99756 0.99758 0.9976
 0.99761 0.99764 0.99765 0.99768 0.99769 0.9977  0.99772 0.99774 0.99779
 0.9978  0.99782 0.99783 0.99784 0.99785 0.99786 0.99787 0.99788 0.9979
 0.99791 0.99796 0.99798 0.998   0.99801 0.99803 0.99808 0.9981  0.99814
 0.99815 0.99817 0.99818 0.9982  0.99822 0.99823 0.99824 0.99828 0.9983
 0.99832 0.99834 0.99836 0.9984  0.99842 0.99845 0.9985  0.99852 0.99854
 0.99855 0.99859 0.9986  0.99864 0.99865 0.9987  0.99878 0.9988  0.99888
 0.9989  0.99892 0.999   0.99901 0.9991  0.99914 0.99915 0.99918 0.9992
 0.99922 0.99925 0.9993  0.99935 0.99938 0.99939 0.9994  0.9995  0.9996
 0.99965 0.9997  0.99974 0.99975 0.99976 0.9998  0.9999  1.      1.00005
 1.0001  1.00012 1.00015 1.0002  1.00024 1.00025 1.0003  1.0004  1.0006
 1.0008  1.001   1.0014  1.0015  1.0018  1.0021  1.0022  1.00242 1.0026
 1.00289 1.00315 1.0032  1.00369]
pH: [2.74 2.86 2.87 2.88 2.89 2.9  2.92 2.93 2.94 2.95 2.98 2.99 3.   3.01
 3.02 3.03 3.04 3.05 3.06 3.07 3.08 3.09 3.1  3.11 3.12 3.13 3.14 3.15
 3.16 3.17 3.18 3.19 3.2  3.21 3.22 3.23 3.24 3.25 3.26 3.27 3.28 3.29
 3.3  3.31 3.32 3.33 3.34 3.35 3.36 3.37 3.38 3.39 3.4  3.41 3.42 3.43
 3.44 3.45 3.46 3.47 3.48 3.49 3.5  3.51 3.52 3.53 3.54 3.55 3.56 3.57
 3.58 3.59 3.6  3.61 3.62 3.63 3.66 3.67 3.68 3.69 3.7  3.71 3.72 3.74
 3.75 3.78 3.85 3.9  4.01]
sulphates: [0.33 0.37 0.39 0.4  0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51
 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65
 0.66 0.67 0.68 0.69 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79
 0.8  0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93
 0.94 0.95 0.96 0.97 0.98 0.99 1.   1.01 1.02 1.03 1.04 1.05 1.06 1.07
 1.08 1.09 1.1  1.11 1.12 1.13 1.14 1.15 1.16 1.17 1.18 1.2  1.22 1.26
 1.28 1.31 1.33 1.34 1.36 1.56 1.59 1.61 1.62 1.95 1.98 2.  ]
alcohol: [ 8.4         8.5         8.7         8.8         9.          9.05
  9.1         9.2         9.23333333  9.25        9.3         9.4
  9.5         9.55        9.56666667  9.6         9.7         9.8
  9.9         9.95       10.         10.03333333 10.1        10.2
 10.3        10.4        10.5        10.55       10.6        10.7
 10.75       10.8        10.9        11.         11.06666667 11.1
 11.2        11.3        11.4        11.5        11.6        11.7
 11.8        11.9        11.95       12.         12.1        12.2
 12.3        12.4        12.5        12.6        12.7        12.8
 12.9        13.         13.1        13.2        13.3        13.4
 13.5        13.56666667 13.6        14.         14.9       ]
quality: [3 4 5 6 7 8]

- Edit those columns (ex: fixed acidity -> fixed_acidity )

## 3. Phân tích dữ liệu (Analyze Data)

### 3.1. Thống kê mô tả (Descriptive Statistics)

#### (1) **Hiển thị một số thông tin về dữ liệu**
+ Số dòng, số cột của dữ liệu
+ Kiểu dữ liệu của từng cột
+ 5 dòng đầu và 5 dòng cuối của bảng dữ liệu
+ Thông tin chung về dữ liệu

In [19]:
# shape
print(f'+ Shape: {winequality_df.shape}')
# head, tail
print(f'+ Contents: ')
display.display(winequality_df.head(5))
display.display(winequality_df.tail(5))
# info
winequality_df.info()

+ Shape: (1599, 12)
+ Contents:

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

**Nhận xét**:
+ Dữ liệu có 11 tính chất để phân lớp: Fixed acidity (g/L), Volatile acidity , Citric acid, Residual sugar, Chlorides, Free sulfur dioxide, Total sulfur dioxide, Density, pH, Sulphates (SO₄²⁻), Alcohol    
+ Tổng số dòng dữ liệu là 1599 dòng
+ Dữ liệu để phân lớp ở cột quality

#### (2) **Kiểm tra tính toàn vẹn của dữ liệu**
+ Dữ liệu có bị trùng lặp không? Hiển thị dòng bị vi phạm.
+ Dữ liệu có tồn tại giá trị Null không? Hiển thị dòng bị vi phạm.
+ Dữ liệu có tồn tại giá trị NaN không? Hiển thị dòng bị vi phạm.

In [6]:
has_null = winequality_df.isnull().sum().any()
has_nan  = winequality_df.isna().sum().any()
n_duplicated = winequality_df.duplicated().sum()
print(f'Tính toàn vẹn dữ liệu:')
print(f'+ Có giá trị Null: {has_null}')
if has_null:
    display.display(winequality_df[winequality_df.isnull().any(axis=1)])
print(f'+ Có giá trị Nan: {has_nan}')
if has_nan:
    display.display(winequality_df[winequality_df.isna().any(axis=1)])
print(f'+ Số dòng trùng: {n_duplicated}')

Tính toàn vẹn dữ liệu:
+ Có giá trị Null: False
+ Có giá trị Nan: False
+ Số dòng trùng: 244

**Nhận xét**:
+ Dữ liệu co 244 bị trùng và không có giá trị rỗng (NaN, Null)